version: "3"

services:
  mysql:
    container_name: rideplus-mysql
    image: mysql:${MYSQL_VERSION:-8.0.23}
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-rideplus}
      MYSQL_USER: ${MYSQL_USER:-rideplus}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-rideplus}
