// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type User struct {
	ID     *string `json:"id,omitempty"`
	Email  *string `json:"email,omitempty"`
	UserID *string `json:"userId,omitempty"`
}

type UserInput struct {
	Email  *string `json:"email,omitempty"`
	UserID *string `json:"userId,omitempty"`
}
