name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: Lint Frontend

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./RidePlus
        run: npm ci

      - name: Run ESLint
        working-directory: ./RidePlus
        run: npm run lint

  prettier:
    runs-on: ubuntu-latest
    name: Check Frontend Format

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./RidePlus
        run: npm ci

      - name: Run Prettier
        working-directory: ./RidePlus
        run: npm run format:check

  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck Frontend

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./RidePlus
        run: npm ci

      - name: Run TypeScript
        working-directory: ./RidePlus
        run: npm run typecheck

  golangci:
    runs-on: ubuntu-latest
    name: Lint Backend

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: false

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          working-directory: server

  gofmt:
    runs-on: ubuntu-latest
    name: Check Backend Format

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Check gofmt
        run: if [ gofmt -l -s . | wc -l -gt 0 ]; then exit 1; fi
